# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  name: Advancement-Trophies-Reforged

  description:

  homepage:

  private: true

  has_issues: true

  has_projects: true

  has_wiki: true

  has_downloads: true

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

  delete_branch_on_merge: true

  enable_automated_security_fixes: true

  enable_vulnerability_alerts: true

labels:
  - name: "type/bug"
    color: "#d73a4a"
    description: "Something isn't working as expected."

  - name: "type/suggestion"
    color: "#f6ea4d"
    description: "An idea or request for a new feature."

  - name: "type/improvement"
    color: "#037571"
    description: "An improvement to an existing feature."

  - name: "type/question"
    color: "#d876e3"
    description: "A question or request for more information."

  - name: "type/documentation"
    color: "#0075ca"
    description: "Related to creating or updating documentation."

  # --- Priority ---
  - name: "priority/high"
    color: "#b22222"
    description: "A critical issue that needs immediate attention."

  - name: "priority/medium"
    color: "#ff8c00"
    description: "A normal priority issue."

  - name: "priority/low"
    color: "#87cefa"
    description: "A low priority issue that can be addressed when time permits."

  # --- Status ---
  - name: "status/confirmed"
    color: "#228b22"
    description: "The reported issue has been confirmed and needs a fix."

  - name: "status/in-progress"
    color: "#f8c300"
    description: "Work is currently in progress."

  - name: "status/needs-info"
    color: "#fbca04"
    description: "More information is needed from the reporter."

  - name: "status/duplicate"
    color: "#cfd3d7"
    description: "This is a duplicate of another issue or pull request."

  - name: "status/wontfix"
    color: "#ffffff"
    description: "This will not be fixed."

  # --- For Contributors ---
  - name: "good first issue"
    color: "#7057ff"
    description: "Good for first-time contributors."
  - name: "help wanted"
    color: "#008672"
    description: "Help from the community is wanted."

  # --- Area (Customize for your project) ---
  - name: "area/ui"
    color: "#c2e0c6"
    description: "Related to the user interface or user experience."
  - name: "area/api"
    color: "#c2e0c6"
    description: "Related to the API."
  - name: "area/performance"
    color: "#c2e0c6"
    description: "Related to performance."