plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.107'
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    maven {
        name = "Curse Maven"
        url = "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url "https://maven.blamejared.com/"
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()

            gameDirectory = project.file("run/client")
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        client2 {
            client()

            gameDirectory = project.file("run/client2")
            programArguments.addAll("--username", "Dev2")
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()

            gameDirectory = project.file("run/server")
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"

            gameDirectory = project.file("run/gameTestServer")
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()

            gameDirectory = project.file("run/data")
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            logLevel = org.slf4j.event.Level.DEBUG

            systemProperty 'mixin.debug.verbose', 'true'
            systemProperty 'mixin.debug.export', 'true'
            systemProperty 'mixin.dumpTargetOnFailure', 'true'
//            systemProperty 'mixin.debug', 'true'

        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }


dependencies {
    implementation "tschipp.carryon:carryon-${loader_name}-${minecraft_version}:${carryon_version}"

    implementation "maven.modrinth:sophisticated-backpacks:CYOnGzwN"
    implementation "maven.modrinth:sophisticated-core:qi2pvRvC"
    implementation "curse.maven:curios-309927:6529130"

    implementation "maven.modrinth:citadel-(1.21.1-port):mIylVpkN"
    implementation "maven.modrinth:alexs-mobs(1.21.1):KSgki4uc"
    implementation "maven.modrinth:alexs-caves-(unofficial-port):pC1MYhqR"
    // implementation "maven.modrinth:better-advancements:FjTYILOi"

    if (!gradle.startParameter.taskNames.contains("runData")) {
        runtimeOnly "curse.maven:configured-457570:5873783"
        runtimeOnly "curse.maven:nbt-autocomplete-813557:5957930"
        runtimeOnly "curse.maven:create-328085:6641610"
    }
}



tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}



publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
