org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)


mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=advancementtrophies
mod_name=Advancement Trophies Reforged
mod_license=The MIT License
mod_version=1.2.0
mod_group_id=io.github.hikoma0000
mod_authors=hikoma0000
mod_description=Earn trophies of varying rarities for completing advancements.


loader_name=forge
carryon_version=2.1.2.7
jei_version=15.20.0.112
cloth_config_version=11.1.136
