org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.219
neo_version_range=[21,)
loader_version_range=[4,)

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=advancementtrophies
mod_name=Advancement Trophies Reforged
mod_license=The MIT License
mod_version=1.3.0
mod_group_id=io.github.hikoma0000
mod_authors=hikoma0000
mod_description=Earn trophies of varying rarities for completing advancements.


loader_name=neoforge
carryon_version=2.2.2.11
jei_version=
cloth_config_version=

